/* SPDX-License-Identifier: Apache-2.0 */

#ifndef ZEPHYR_INCLUDE_DT_BINDINGS_DMA_INGCHIPS_DMA_H_
#define ZEPHYR_INCLUDE_DT_BINDINGS_DMA_INGCHIPS_DMA_H_

#define INGCHIPS_DMA_REQ_UART0_RX 0
#define INGCHIPS_DMA_REQ_UART1_RX 1
#define INGCHIPS_DMA_REQ_UART0_TX 8
#define INGCHIPS_DMA_REQ_UART1_TX 9

#endif /* ZEPHYR_INCLUDE_DT_BINDINGS_DMA_INGCHIPS_DMA_H_ */
